app:
  build: ./app
  tty: true
  stdin_open: true
  links:
    - redis
  expose:
    - "7001"
  restart: always
  command: node service.js 

nginx:
  build: ./nginx
  links:
    - app
  ports:
    - "80:80"
  restart: always

redis:
  image: redis
