app:
  image: app:build
  tty: true
  stdin_open: true
  expose:
    - "7001"
  restart: always
  command: node service.js 

nginx:
  build: ./nginx
  links:
    - app
  ports:
    - "80:80"
  restart: always
